version: '3'
services:
  db:
    image: mysql:8
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=gateway01.ap-southeast-1.prod.aws.tidbcloud.com
      - DB_PORT=4000
      - DB_USERNAME=4EtXipGy3sHBQbi.root
      - DB_PASSWORD=r3KPlKroxv2VrS2N
      - DB_DATABASE=test
    volumes:
      - /tmp/social_network/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  social_network:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/social_network
      - /tmp/social_network/mysqld:/run/mysqld
    depends_on:
      - db