# version: '3.9'

# services:
#   db:
#     image: mysql:8
#     ports:
#       - "3307:3306"
#     environment:
#       - MYSQL_DATABASE='social_network'
#       - MYSQL_USER='root'
#       - MYSQL_PASSWORD='password'
#       - MYSQL_ROOT_PASSWORD='password'
#       - MYSQL_HOST=''
#     volumes:
#       - /tmp/app/mysqld:/var/run/mysqld
#       - . /db:/var/lib/mysql
#   # db:
#   #   image: mysql:8.0.11
#   #   container_name: db
#   #   restart: always
#   #   volumes:
#   #     - data:/var/lib/mysql
#   #   environment:
#   #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#   #     MYSQL_DATABASE: ${MYSQL_DATABASE}
#   #     MYSQL_USER: ${MYSQL_USER}
#   #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#   #   ports:
#   #     - "3307:3306"
#   #   healthcheck:
#   #     test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
#   #     timeout: 20s
#   #     retries: 10

#   # web:
#   #   build: .
#   #   command: python manage.py runserver 0.0.0.0:8000
#   #   volumes:
#   #     - .:/social_network
#   #   restart: always
#   #   ports:
#   #     - "8000:8000"
#   #   depends_on:
#   #    - db
  
#   social_network_backend:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     container_name: social_network
#     command: sh -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
#     restart: always
#     volumes:
#       - .:/social_network
#       - /tmp/app/mysqld:/run/mysqld
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     depends_on:
#       - db
#           #condition: 'service_healthy'
# volumes:
#   data:

version: '3'
services:
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - DB_HOST=gateway01.ap-southeast-1.prod.aws.tidbcloud.com
      - DB_PORT=4000
      - DB_USERNAME=4EtXipGy3sHBQbi.root
      - DB_PASSWORD=r3KPlKroxv2VrS2N
      - DB_DATABASE=test
      # - MYSQL_DATABASE=social_network
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=password
      # - MYSQL_ROOT_PASSWORD=password
      # - MYSQL_HOST='db'
    volumes:
      - /tmp/social_network/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  social_network:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/social_network
      - /tmp/social_network/mysqld:/run/mysqld
    depends_on:
      - db